[project]
authors = [{name = "Fabian", email = "132886103+FabianKruger@users.noreply.github.com"}]
dependencies = []
name = "molopt_agent"
requires-python = ">= 3.11"
version = "0.1.0"

[project.scripts]
molopt = "molopt_agent.main:main"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tool.pixi.pypi-dependencies]
molopt_agent = { path = ".", editable = true }
langgraph = ">=0.5"

[tool.pixi.tasks]

[tool.pixi.target.linux-64.dependencies]
python = "3.13.*"

[tool.pixi.target.osx-arm64.dependencies]
python = "3.13.*"

[tool.pixi.dependencies]
transformers = ">=4.57.3,<5"
rdkit = ">=2025.9.3,<2026"
langchain-openai = ">=0.3.35,<2"
python-dotenv = ">=1.2.1,<2"
pyyaml = ">=6.0.3,<7"
pytorch = "*"
