from typing import Protocol
from ..state import WorkflowState
from ..oracles.base import OracleResult


class Objective(Protocol):
    name: str

    def first_message(self) -> str: ...
    def evaluate(self, state: WorkflowState) -> OracleResult: ...
    def build_feedback(self, state: WorkflowState, result: OracleResult) -> str: ...
    def is_done(self, state: WorkflowState, result: OracleResult) -> bool: ...
    def max_iterations(self) -> int: ...
